Public Class Production_day_wise

    Private Sub btn_go_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btn_go.Click
        If rad_qty.Checked = True Then


            sql = "  select jan_orgcode(ORGANIZATION_ID)org,item_no,ORGANIZATION_ID,  "
            sql &= "case when   MAKE_BUY ='ASIS' then 'ASIS' when LEVEL_5='Spares' then  'Spares'  else 'Product' end PROD_CAT  "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='1-sep-2016'then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_1    "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='2-sep-2016'then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_2  "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='3-sep-2016'then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_3   "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='4-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_4   "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='5-sep-2016'then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_5  "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='6-sep-2016'then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_6  "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='7-sep-2016'then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_7  "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='8-sep-2016'then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_8  "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='9-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_9  "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='10-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_10 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='11-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_11 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='12-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_12 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='13-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_13 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='14-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_14 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='15-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_15 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='16-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_16 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='17-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_17 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='18-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_18 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='19-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_19 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='20-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_20 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='21-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_21 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='22-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_22 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='23-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_23 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='24-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_24"
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='25-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_25 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='26-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_26 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='27-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_27 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='28-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_28 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='29-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_29 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='30-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_30 "
            sql &= ",clp p_rate  "
            sql &= "from (  "
            sql &= "select a.*   "
            sql &= ",NVL(( select DECODE(COUNT(*),0,'Make','ASIS') from JAN_BUY_AND_SELL_PRODUCTS where INVENTORY_ITEM_ID=a.INVENTORY_ITEM_ID),'Make')MAKE_BUY  "
            sql &= "from JAN_PROD_VAL_NEW  a where TRUNC(TRANSACTION_DATE)>='1-SEP-2016' "
            sql &= ")   "
            sql &= "group by JAN_ORGCODE(ORGANIZATION_ID), ITEM_NO, ORGANIZATION_ID, case when   MAKE_BUY ='ASIS' then 'ASIS' when LEVEL_5='Spares' then  'Spares'  else 'Product' end, CLP  "
            sql &= " union "
            sql &= "select JAN_ORGCODE(ORGANIZATION_ID)ORG,JAN_ITEMNAME(INVENTORY_ITEM_ID)ITEM_NO,ORGANIZATION_ID,  "
            sql &= "        'IO' PROD_CAT  "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='1-sep-2016'then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_1    "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='2-sep-2016'then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_2  "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='3-sep-2016'then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_3   "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='4-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_4   "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='5-sep-2016'then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_5  "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='6-sep-2016'then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_6  "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='7-sep-2016'then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_7  "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='8-sep-2016'then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_8  "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='9-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_9  "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='10-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_10 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='11-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_11 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='12-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_12"
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='13-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_13 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='14-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_14 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='15-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_15 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='16-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_16 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='17-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_17 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='18-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_18 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='19-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_19 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='20-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_20 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='21-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_21 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='22-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_22 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='23-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_23 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='24-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_24"
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='25-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_25 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='26-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_26 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='27-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_27 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='28-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_28 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='29-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_29 "
            sql &= ",SUM(case when TRUNC(TRANSACTION_DATE)='30-sep-2016' then TRANSACTION_QUANTITY else 0 end )PRODN_QTY_SEP_30 "


            sql &= ",nvl((select round(pval,2) from jan_prate where INVENTORY_ITEM_ID=a.INVENTORY_ITEM_ID),0) P_RATE from MTL_MATERIAL_TRANSACTIONS a  "
            sql &= "where TRUNC(TRANSACTION_DATE)>='1-sep-2016' and TRANSACTION_TYPE_ID=44 and    "
            sql &= "SUBINVENTORY_CODE in ('IO-FC','IO-M-FC') group by JAN_ORGCODE(ORGANIZATION_ID), INVENTORY_ITEM_ID, ORGANIZATION_ID, 'IO'"
        End If

        ds = SQL_SELECT("data", sql)
        dgv1.DataSource = ds.Tables("data")
    End Sub
End Class